services:
  supnode1:
    build: .
    ports:
      - 8888
      - 5005:5005
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./target/dockerhomes/supnode1:/opt/app
      - ./target/supcrypto.jar:/opt/app/supcrypto.jar:ro
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -Djava.security.egd=file:/dev/./urandom -jar /opt/app/supcrypto.jar
    tty: true
  supnode2:
    build: .
    ports:
      - 8888
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./target/dockerhomes/supnode2:/opt/app
      - ./target/supcrypto.jar:/opt/app/supcrypto.jar:ro
    entrypoint: java -jar /opt/app/supcrypto.jar
    tty: true
